spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 4
          max-interval: 10s
          multiplier: 2
application:
  rabbitmq:
    queue: direct-orders-queue-1

server:
  port: 8886
